export const Collections = {
  companies: 'companies',
  users: 'users',
  clients: 'clients',
  suppliers: 'suppliers',
  categories: 'categories',
  products: 'products',
  lossControls: 'lossControls',
  sales: 'sales',
  saleItems: 'saleItems',
  purchases: 'purchases',
  purchaseItems: 'purchaseItems',
  cashRegisters: 'cashRegisters',
  cashMovements: 'cashMovements',
  receivables: 'receivables',
  payables: 'payables',
  tableModules: 'tableModules',
  orders: 'orders',
  orderItems: 'orderItems',
  productions: 'productions',
  productionConsumptions: 'productionConsumptions',
  inventory: 'inventory',
} as const

export type CollectionName = (typeof Collections)[keyof typeof Collections]
